export const INCREAMENT_COUNTER='INCREAMENT_COUNTER'
export const DECREAMENT_COUNTER='DECREAMENT_COUNTER'
export const FACILITIES_DATA='FACILITIES_DATA'
export const REMOVE_DATA='REMOVE_DATA'
export const EDIT_DATA='EDIT_DATA'
export const LOADING_DATA='LOADING_DATA'
export const GET_PRODUCTS='GET_PRODUCTS'
export const REMOVE_PRODUCTS='REMOVE_PRODUCTS'
export const EDIT_PRODUCTS='EDIT_PRODUCTS'
export const LOADING_PRODUCTS='LOADING_PRODUCTS'





