export const INCREAMENT_COUNTER='INCREAMENT_COUNTER'
export const DECREAMENT_COUNTER='DECREAMENT_COUNTER'
export const FACILITIES_DATA='FACILITIES_DATA'
export const REMOVE_DATA='REMOVE_DATA'
export const EDIT_DATA='EDIT_DATA'


