export const TOGGLE_THEME='TOGGLE_THEME'
export const ADDINTRO='ADDINTRO'
export const EDITINTRO='EDITINTRO'
export const DELETEINTRO='DELETEINTRO'
export const GETINTRO='GETINTRO'
export const ADD_CONTACT='ADD_CONTACT'
export const EDIT_CONTACT='EDIT_CONTACT'
export const DELETE_CONTACT='DELETE_CONTACT'
export const GET_CONTACT='GET_CONTACT'



